namespace :db do
  desc "Erase and fill login table"
  task :populate_login => :environment do
    User.destroy_all
    
    # Cargos
    @cargo1 = Cargo.find(1)
    @cargo2 = Cargo.find(2)
    @cargo3 = Cargo.find(3)
    puts Cargo.all

    # Setores
    @setor1 = Setor.find(1)
    @setor2 = Setor.find(2)
    @setor3 = Setor.find(3)
    @setor4 = Setor.find(4)
    @setor5 = Setor.find(5)
    @setor6 = Setor.find(6)
    @setor7 = Setor.find(7)
    @setor8 = Setor.find(8)
    @setor9 = Setor.find(9)
    @setor10 = Setor.find(10)
    @setor11 = Setor.find(11)
    @setor12 = Setor.find(12)
    @setor13 = Setor.find(13)
    @setor14 = Setor.find(14)
    @setor15 = Setor.find(15)
    puts Setor.all

    # Insere usuários
    User.create(nome: "HERBERTH LOIOLA CASTRO", username: "herberth.castro", setor: @setor1, email: "herberth.castro@comunicacoes.gov.br", cargo: @cargo1, password: "herberth.castro", password_confirmation: "herberth.castro")
    User.create(nome: "THIAGO RIZZA SILVA", username: "thiago.silva", setor: @setor1, email: "thiago.silva@comunicacoes.gov.br", cargo: @cargo1, password: "thiago.silva", password_confirmation: "thiago.silva")
    User.create(nome: "EDIVAL MARQUES MOREIRA", username: "edival.moreira", setor: @setor1, email: "edival.moreira@comunicacoes.gov.br", cargo: @cargo1, password: "edival.moreira", password_confirmation: "edival.moreira")
    User.create(nome: "CARLOS ALBERTO M. GOLD JR.", username: "carlos.gold", setor: @setor2, email: "carlos.gold@comunicacoes.gov.br", cargo: @cargo1, password: "carlos.gold", password_confirmation: "carlos.gold")
    User.create(nome: "VITOR TORRES DA SILVA", username: "vitor.torres", setor: @setor2, email: "vitor.torres@comunicacoes.gov.br", cargo: @cargo1, password: "vitor.torres", password_confirmation: "vitor.torres")
    User.create(nome: "REGINALDO NERI SILVA", username: "reginaldo.neri", setor: @setor2, email: "reginaldo.neri@comunicacoes.gov.br", cargo: @cargo2, password: "reginaldo.neri", password_confirmation: "reginaldo.neri")
    User.create(nome: "ADRIANO NOGUEIRA DE SOUZA", username: "adriano.souza", setor: @setor2, email: "adriano.souza@comunicacoes.gov.br", cargo: @cargo1, password: "adriano.souza", password_confirmation: "adriano.souza")
    User.create(nome: "PATRICIA BRITO DE AVILA", username: "patricia.avila", setor: @setor1, email: "patricia.avila@comunicacoes.gov.br", cargo: @cargo1, password: "patricia.avila", password_confirmation: "patricia.avila")
    User.create(nome: "ALDENNE F. DE SILVERIO E OLVEIRA", username: "aldenne.oliveira", setor: @setor2, email: "aldenne.oliveira@comunicacoes.gov.br", cargo: @cargo1, password: "aldenne.oliveira", password_confirmation: "aldenne.oliveira")
    User.create(nome: "ALDO CESAR RABELO NORA", username: "aldo.nora", setor: @setor2, email: "aldo.nora@comunicacoes.gov.br", cargo: @cargo1, password: "aldo.nora", password_confirmation: "aldo.nora")
    User.create(nome: "ALEXANDRE MIRANDA F. O. BARROS", username: "alexandre.barros", setor: @setor2, email: "alexandre.barros@comunicacoes.gov.br", cargo: @cargo1, password: "alexandre.barros", password_confirmation: "alexandre.barros")
    User.create(nome: "ANTONIO CARLOS SALOMÃO MANGIA", username: "antonio.mangia", setor: @setor2, email: "antonio.mangia@comunicacoes.gov.br", cargo: @cargo1, password: "antonio.mangia", password_confirmation: "antonio.mangia")
    User.create(nome: "ARTHUR ISBERT LOPES", username: "arthur.lopes", setor: @setor2, email: "arthur.lopes@comunicacoes.gov.br", cargo: @cargo3, password: "arthur.lopes", password_confirmation: "arthur.lopes")
    User.create(nome: "EVA MARIA DOS SANTOS", username: "eva.santos", setor: @setor3, email: "eva.santos@comunicacoes.gov.br", cargo: @cargo2, password: "eva.santos", password_confirmation: "eva.santos")
    User.create(nome: "LEONARDO AZEVEDO DOS SANTOS", username: "leonardo.santos", setor: @setor2, email: "leonardo.santos@comunicacoes.gov.br", cargo: @cargo3, password: "leonardo.santos", password_confirmation: "leonardo.santos")
    User.create(nome: "MIRACELI DANTAS CRUZ", username: "miraceli.cruz", setor: @setor2, email: "miraceli.cruz@comunicacoes.gov.br", cargo: @cargo1, password: "miraceli.cruz", password_confirmation: "miraceli.cruz")
    User.create(nome: "ODAIR JOSÉ RODRIGUES CAMPOS JR", username: "odair.junior", setor: @setor2, email: "odair.junior@comunicacoes.gov.br", cargo: @cargo3, password: "odair.junior", password_confirmation: "odair.junior")
    User.create(nome: "OSMAR DE BARROS MAFRA JUNIOR", username: "osmar.junior", setor: @setor2, email: "osmar.junior@comunicacoes.gov.br", cargo: @cargo2, password: "osmar.junior", password_confirmation: "osmar.junior")
    User.create(nome: "RICARDO MESQUITA MUNIZ", username: "ricardo.muniz", setor: @setor2, email: "ricardo.muniz@comunicacoes.gov.br", cargo: @cargo1, password: "ricardo.muniz", password_confirmation: "ricardo.muniz")
    User.create(nome: "ROSANGELA PETRI DUARTE", username: "rosangela.duarte", setor: @setor2, email: "rosangela.duarte@comunicacoes.gov.br", cargo: @cargo1, password: "rosangela.duarte", password_confirmation: "rosangela.duarte")
    User.create(nome: "VITOR AUGUSTO BISPO DA SILVA", username: "vitor.silva", setor: @setor2, email: "vitor.silva@comunicacoes.gov.br", cargo: @cargo1, password: "vitor.silva", password_confirmation: "vitor.silva")
    User.create(nome: "ELLEN KAROLINY C. DAMASCENO", username: "ellen.damasceno", setor: @setor2, email: "ellen.damasceno@comunicacoes.gov.br", cargo: @cargo3, password: "ellen.damasceno", password_confirmation: "ellen.damasceno")
    User.create(nome: "CARLOS FELIPE ILHA PEREIRA", username: "carlos.pereira", setor: @setor2, email: "carlos.pereira@comunicacoes.gov.br", cargo: @cargo3, password: "carlos.pereira", password_confirmation: "carlos.pereira")
    User.create(nome: "MARIA IVAGNA FERREIRA M. REIS", username: "ivagna.mendes", setor: @setor3, email: "ivagna.mendes@comunicacoes.gov.br", cargo: @cargo1, password: "ivagna.mendes", password_confirmation: "ivagna.mendes")
    User.create(nome: "ROSELI APARECIDA F.DE OLIVEIRA", username: "roseli.oliveira", setor: @setor2, email: "roseli.oliveira@comunicacoes.gov.br", cargo: @cargo2, password: "roseli.oliveira", password_confirmation: "roseli.oliveira")
    User.create(nome: "MARCIELLY SILVA", username: "marcielly.silva", setor: @setor2, email: "marcielly.silva@comunicacoes.gov.br", cargo: @cargo2, password: "marcielly.silva", password_confirmation: "marcielly.silva")
    User.create(nome: "ARIAN ASSUNÇÃO SANTOS", username: "arian.santos", setor: @setor3, email: "arian.santos@comunicacoes.gov.br", cargo: @cargo1, password: "arian.santos", password_confirmation: "arian.santos")
    User.create(nome: "EDIRCE PEREIRA DOS REIS SOUZA ", username: "edirce.souza", setor: @setor2, email: "edirce.souza@comunicacoes.gov.br", cargo: @cargo2, password: "edirce.souza", password_confirmation: "edirce.souza")
    User.create(nome: "NEIRIANE DA SILVA ALMEIDA", username: "neiriane.almeida", setor: @setor2, email: "neiriane.almeida@comunicacoes.gov.br", cargo: @cargo2, password: "neiriane.almeida", password_confirmation: "neiriane.almeida")
    User.create(nome: "LUCIENE BASTOS DOS SANTOS", username: "luciene", setor: @setor12, email: "luciene@comunicacoes.gov.br", cargo: @cargo2, password: "luciene", password_confirmation: "luciene")
    User.create(nome: "ILCA TATIANA ALVES DOS SANTOS ", username: "ilca.santos", setor: @setor2, email: "ilca.santos@comunicacoes.gov.br", cargo: @cargo2, password: "ilca.santos", password_confirmation: "ilca.santos")
    User.create(nome: "SUELI OLIVEIRA BRAGA ", username: "sueli.braga", setor: @setor6, email: "sueli.braga@comunicacoes.gov.br", cargo: @cargo2, password: "sueli.braga", password_confirmation: "sueli.braga")
    User.create(nome: "TALES FERREIRA ROCHA SOARES ", username: "tales.soares", setor: @setor2, email: "tales.soares@comunicacoes.gov.br", cargo: @cargo3, password: "tales.soares", password_confirmation: "tales.soares")
    User.create(nome: "VALÉRIA FERREIRA DE MIRANDA ", username: "valeria.miranda", setor: @setor2, email: "valeria.miranda@comunicacoes.gov.br", cargo: @cargo3, password: "valeria.miranda", password_confirmation: "valeria.miranda")
    User.create(nome: "JOSÉ UELBES DA CONCEIÇÃO BRITO", username: "jose.brito", setor: @setor2, email: "jose.brito@comunicacoes.gov.br", cargo: @cargo3, password: "jose.brito", password_confirmation: "jose.brito")
    User.create(nome: "ANA CAROLINA DE SOUZA BRITO ", username: "ana.brito", setor: @setor2, email: "ana.brito@comunicacoes.gov.br", cargo: @cargo3, password: "ana.brito", password_confirmation: "ana.brito")
    User.create(nome: "RAQUEL SOARES DA SILVA", username: "raquel.silva", setor: @setor2, email: "raquel.silva@comunicacoes.gov.br", cargo: @cargo2, password: "raquel.silva", password_confirmation: "raquel.silva")
    User.create(nome: "EVA CARLA CORREIA DE FREITAS", username: "eva.freitas", setor: @setor3, email: "eva.freitas@comunicacoes.gov.br", cargo: @cargo1, password: "eva.freitas", password_confirmation: "eva.freitas")
    User.create(nome: "VANEIDE LOPES DA ROCHA", username: "vaneide.rocha", setor: @setor2, email: "vaneide.rocha@comunicacoes.gov.br", cargo: @cargo2, password: "vaneide.rocha", password_confirmation: "vaneide.rocha")
    User.create(nome: "ANDERSON VILAS BOAS DA SILVA", username: "anderson.silva", setor: @setor5, email: "anderson.silva@comunicacoes.gov.br", cargo: @cargo1, password: "anderson.silva", password_confirmation: "anderson.silva")
    User.create(nome: "DIEGO FERNANDES CARNEIRO SILVA", username: "diego.silva", setor: @setor1, email: "diego.silva@comunicacoes.gov.br", cargo: @cargo1, password: "diego.silva", password_confirmation: "diego.silva")
    User.create(nome: "SAYONARA LEONEZ MEDEIROS COELHO", username: "sayonara", setor: @setor4, email: "sayonara@comunicacoes.gov.br", cargo: @cargo1, password: "sayonara", password_confirmation: "sayonara")
    User.create(nome: "NUMERACAO", username: "numeracao.gtdi", setor: @setor5, email: "numeracao.gtdi@comunicacoes.gov.br", cargo: @cargo1, password: "numeracao.gtdi", password_confirmation: "numeracao.gtdi")
    User.create(nome: "ZULENE BORGES DA SILVA", username: "zulene.silva", setor: @setor3, email: "zulene.silva@comunicacoes.gov.br", cargo: @cargo2, password: "zulene.silva", password_confirmation: "zulene.silva")
    User.create(nome: "TANIA APARECIDA DE PAULA", username: "taniaa", setor: @setor3, email: "taniaa@comunicacoes.gov.br", cargo: @cargo2, password: "taniaa", password_confirmation: "taniaa")
    User.create(nome: "KEZIA URANI GOMES", username: "kezia.gomes", setor: @setor13, email: "kezia.gomes@comunicacoes.gov.br", cargo: @cargo2, password: "kezia.gomes", password_confirmation: "kezia.gomes")
    User.create(nome: "JOSE ANCELMO NOGUEIRA", username: "jose", setor: @setor13, email: "jose@comunicacoes.gov.br", cargo: @cargo1, password: "jose", password_confirmation: "jose")
    User.create(nome: "YASMINI ESTER DO NASCIMENTO DA", username: "yasmini", setor: @setor13, email: "yasmini@comunicacoes.gov.br", cargo: @cargo1, password: "yasmini", password_confirmation: "yasmini")
    User.create(nome: "MARCELA CAMARA RORIZ", username: "marcela.roriz", setor: @setor4, email: "marcela.roriz@comunicacoes.gov.br", cargo: @cargo1, password: "marcela.roriz", password_confirmation: "marcela.roriz")
    User.create(nome: "SISTVD", username: "sistvd.gtdi", setor: @setor14, email: "sistvd.gtdi@comunicacoes.gov.br", cargo: @cargo1, password: "sistvd.gtdi", password_confirmation: "sistvd.gtdi")
    User.create(nome: "GTFT", username: "gtft.gtdi", setor: @setor1, email: "gtft.gtdi@comunicacoes.gov.br", cargo: @cargo1, password: "gtft.gtdi", password_confirmation: "gtft.gtdi")
    User.create(nome: "ATENDIMENTO", username: "atendimento.gtdi", setor: @setor1, email: "atendimento.gtdi@comunicacoes.gov.br", cargo: @cargo1, password: "atendimento.gtdi", password_confirmation: "atendimento.gtdi")
    User.create(nome: "EDIVAL MARQUES", username: "edival.gtft", setor: @setor7, email: "edival.gtft@comunicacoes.gov.br", cargo: @cargo1, password: "edival.gtft", password_confirmation: "edival.gtft")
    User.create(nome: "DIEGO FERNANDES", username: "diego.gtft", setor: @setor7, email: "diego.gtft@comunicacoes.gov.br", cargo: @cargo1, password: "diego.gtft", password_confirmation: "diego.gtft")
    User.create(nome: "FERNANDO", username: "fernando.gtft", setor: @setor7, email: "fernando.gtft@comunicacoes.gov.br", cargo: @cargo1, password: "fernando.gtft", password_confirmation: "fernando.gtft")
    User.create(nome: "JONATA", username: "jonata.gtft", setor: @setor7, email: "jonata.gtft@comunicacoes.gov.br", cargo: @cargo1, password: "jonata.gtft", password_confirmation: "jonata.gtft")
    User.create(nome: "JUNIOR", username: "junior.gtft", setor: @setor7, email: "junior.gtft@comunicacoes.gov.br", cargo: @cargo1, password: "junior.gtft", password_confirmation: "junior.gtft")
    User.create(nome: "ANTONIO CARLOS", username: "antonio.carlos.gtft", setor: @setor7, email: "antonio.carlos.gtft@comunicacoes.gov.br", cargo: @cargo1, password: "antonio.carlos", password_confirmation: "antonio.carlos")
    User.create(nome: "FABIANO", username: "fabiano.gtft", setor: @setor7, email: "fabiano.gtft@comunicacoes.gov.br", cargo: @cargo1, password: "fabiano.gtft", password_confirmation: "fabiano.gtft")
    User.create(nome: "DAYAL", username: "dayal.gtft", setor: @setor7, email: "dayal.gtft@comunicacoes.gov.br", cargo: @cargo1, password: "dayal.gtft", password_confirmation: "dayal.gtft")
    User.create(nome: "ADRIANO", username: "adriano.gtft", setor: @setor7, email: "adriano.gtft@comunicacoes.gov.br", cargo: @cargo1, password: "adriano.gtft", password_confirmation: "adriano.gtft")
    User.create(nome: "LUCILIO", username: "lucilio.gtft", setor: @setor7, email: "lucilio.gtft@comunicacoes.gov.br", cargo: @cargo1, password: "lucilio.gtft", password_confirmation: "lucilio.gtft")
    User.create(nome: "MARIA CRISTINA", username: "maria.cristina.gtft", setor: @setor7, email: "maria.cristina.gtft@comunicacoes.gov.br", cargo: @cargo1, password: "maria.cristina", password_confirmation: "maria.cristina")
    User.create(nome: "GILSON", username: "gilson.gtft", setor: @setor7, email: "gilson.gtft@comunicacoes.gov.br", cargo: @cargo1, password: "gilson.gtft", password_confirmation: "gilson.gtft")
    User.create(nome: "ELZA", username: "elza.gtft", setor: @setor7, email: "elza.gtft@comunicacoes.gov.br", cargo: @cargo1, password: "elza.gtft", password_confirmation: "elza.gtft")
    User.create(nome: "GERALDO", username: "geraldo.gtft", setor: @setor7, email: "geraldo.gtft@comunicacoes.gov.br", cargo: @cargo1, password: "geraldo.gtft", password_confirmation: "geraldo.gtft")
    User.create(nome: "EMILIO", username: "emilio.gtft", setor: @setor7, email: "emilio.gtft@comunicacoes.gov.br", cargo: @cargo1, password: "emilio.gtft", password_confirmation: "emilio.gtft")
    User.create(nome: "RAFAEL", username: "rafael.gtft", setor: @setor7, email: "rafael.gtft@comunicacoes.gov.br", cargo: @cargo1, password: "rafael.gtft", password_confirmation: "rafael.gtft")
    User.create(nome: "LUIS", username: "luis.gtft", setor: @setor7, email: "luis.gtft@comunicacoes.gov.br", cargo: @cargo1, password: "luis.gtft", password_confirmation: "luis.gtft")
    User.create(nome: "FERNANDA", username: "fernanda.gtft", setor: @setor7, email: "fernanda.gtft@comunicacoes.gov.br", cargo: @cargo1, password: "fernanda.gtft", password_confirmation: "fernanda.gtft")
    User.create(nome: "INES", username: "ines.gtft", setor: @setor7, email: "ines.gtft@comunicacoes.gov.br", cargo: @cargo1, password: "ines.gtft", password_confirmation: "ines.gtft")
    User.create(nome: "LUCIANO", username: "luciano.gtft", setor: @setor7, email: "luciano.gtft@comunicacoes.gov.br", cargo: @cargo1, password: "luciano.gtft", password_confirmation: "luciano.gtft")
    User.create(nome: "PATRICIA", username: "patricia.gtft", setor: @setor7, email: "patricia.gtft@comunicacoes.gov.br", cargo: @cargo1, password: "patricia.gtft", password_confirmation: "patricia.gtft")
    User.create(nome: "CGEO", username: "cgeo", setor: @setor15, email: "cgeo@comunicacoes.gov.br", cargo: @cargo1, password: "cgeo", password_confirmation: "cgeo")
    User.create(nome: "ALMIR COUTINHO POLLIG", username: "almir.pollig", setor: @setor1, email: "almir.pollig@comunicacoes.gov.br", cargo: @cargo1, password: "almir.pollig", password_confirmation: "almir.pollig")
    User.create(nome: "ARMINDO JOSE DOS SANTOS", username: "armindo.santos", setor: @setor6, email: "armindo.santos@comunicacoes.gov.br", cargo: @cargo2, password: "armindo.santos", password_confirmation: "armindo.santos")
    User.create(nome: "BRENDA NOGUEIRA GUERRA", username: "brenda.guerra", setor: @setor6, email: "brenda.guerra@comunicacoes.gov.br", cargo: @cargo3, password: "brenda.guerra", password_confirmation: "brenda.guerra")
    User.create(nome: "CARLOS HENRIQUE DA S. OLIVEIRA", username: "carlosh.oliveira", setor: @setor6, email: "carlosh.oliveira@comunicacoes.gov.br", cargo: @cargo2, password: "carlosh.oliveira", password_confirmation: "carlosh.oliveira")
    User.create(nome: "GABRIEL CRISTOPHY L. DA SILVA", username: "gabriel.silva", setor: @setor6, email: "gabriel.silva@comunicacoes.gov.br", cargo: @cargo2, password: "gabriel.silva", password_confirmation: "gabriel.silva")
    User.create(nome: "GISLENE SOARES MENDES", username: "gislene.mendes", setor: @setor6, email: "gislene.mendes@comunicacoes.gov.br", cargo: @cargo1, password: "gislene.mendes", password_confirmation: "gislene.mendes")
    User.create(nome: "JULIANA SANTOS SALES", username: "juliana.sales", setor: @setor6, email: "juliana.sales@comunicacoes.gov.br", cargo: @cargo1, password: "juliana.sales", password_confirmation: "juliana.sales")
    User.create(nome: "KELLY APARECIDA G. DE OLIVEIRA", username: "kelly.oliveira", setor: @setor6, email: "kelly.oliveira@comunicacoes.gov.br", cargo: @cargo1, password: "kelly.oliveira", password_confirmation: "kelly.oliveira")
    User.create(nome: "WALLACE AMORIM", username: "wallace.amorim", setor: @setor4, email: "wallace.amorim@comunicacoes.gov.br", cargo: @cargo1, password: "wallace.amorim", password_confirmation: "wallace.amorim")
    User.create(nome: "CARLOS ALVES", username: "carlos.alves", setor: @setor1, email: "carlos.alves@comunicacoes.gov.br", cargo: @cargo1, password: "carlos.alves", password_confirmation: "carlos.alves")
    User.create(nome: "IAN SODRÉ GALLINA", username: "ian.gallina", setor: @setor1, email: "ian.gallina@comunicacoes.gov.br", cargo: @cargo1, password: "ian.gallina", password_confirmation: "ian.gallina")
    User.create(nome: "IZAIAS ALVES CARDOSO FILHO", username: "izaias.filho", setor: @setor8, email: "izaias.filho@comunicacoes.gov.br", cargo: @cargo1, password: "izaias.filho", password_confirmation: "izaias.filho")
    User.create(nome: "RAISLA ANDRADE COSTA", username: "raisla.costa", setor: @setor1, email: "raisla.costa@comunicacoes.gov.br", cargo: @cargo1, password: "raisla.costa", password_confirmation: "raisla.costa")
    User.create(nome: "WEBERSON WAYNE NÓBREGA PEIXOTO", username: "weberson.peixoto", setor: @setor8, email: "weberson.peixoto@comunicacoes.gov.br", cargo: @cargo1, password: "weberson.peixoto", password_confirmation: "weberson.peixoto")
    User.create(nome: "VANESSA RODRIGUES MACEDO", username: "vanessa.macedo", setor: @setor9, email: "vanessa.macedo@comunicacoes.gov.br", cargo: @cargo1, password: "vanessa.macedo", password_confirmation: "vanessa.macedo")
    User.create(nome: "LUCIANO DA SILVA ECIENE", username: "luciano.eciene", setor: @setor9, email: "luciano.eciene@comunicacoes.gov.br", cargo: @cargo1, password: "luciano.eciene", password_confirmation: "luciano.eciene")
    User.create(nome: "JUAREZ MORAES DE MEDEIROS", username: "juarez.medeiros", setor: @setor9, email: "juarez.medeiros@comunicacoes.gov.br", cargo: @cargo1, password: "juarez.medeiros", password_confirmation: "juarez.medeiros")
    User.create(nome: "SIBELA LEANDRA PORTELLA MATIAS", username: "sibela.portella", setor: @setor10, email: "sibela.portella@comunicacoes.gov.br", cargo: @cargo1, password: "sibela.portella", password_confirmation: "sibela.portella")
    User.create(nome: "LETÍCIA RIBEIRO CARDOSO", username: "leticia.cardoso", setor: @setor10, email: "leticia.cardoso@comunicacoes.gov.br", cargo: @cargo1, password: "leticia.cardoso", password_confirmation: "leticia.cardoso")
    User.create(nome: "MARIZA OSHIRO", username: "mariza.oshiro", setor: @setor10, email: "mariza.oshiro@comunicacoes.gov.br", cargo: @cargo1, password: "mariza.oshiro", password_confirmation: "mariza.oshiro")
    User.create(nome: "ANA CLARA SILVA LOPES", username: "anaclara.lopes", setor: @setor11, email: "anaclara.lopes@comunicacoes.gov.br", cargo: @cargo1, password: "anaclara.lopes", password_confirmation: "anaclara.lopes")
    User.create(nome: "DILCIMAR FERREIRA R. DE MELLO", username: "dilcimar.mello", setor: @setor11, email: "dilcimar.mello@comunicacoes.gov.br", cargo: @cargo1, password: "dilcimar.mello", password_confirmation: "dilcimar.mello")
    User.create(nome: "LEANDRO PEDRO DE LIMA", username: "leandro.lima", setor: @setor11, email: "leandro.lima@comunicacoes.gov.br", cargo: @cargo1, password: "leandro.lima", password_confirmation: "leandro.lima") 
  end
end