
development:
  database: <%= ENV['DATABASE_USERNAME'] %>_test
  adapter: postgresql
  username: postgres
  password: postgres

test:
  adapter: postgresql
  database: <%= ENV['DATABASE_USERNAME'] %>_development
  username: postgres
  password: postgres

production:
  adapter: postgresql
  database: <%= ENV['DATABASE_USERNAME'] %>_production
  username: postgres
  password: postgres
