class CreateChannels < ActiveRecord::Migration
  def change
    create_table :channels do |t|
      t.string :idtplanobasico
      t.string :idthabilitacao
      t.string :siglaservico
      t.string :numservico
      t.string :siglauf
      t.string :nomemunicipio
      t.string :nomedistrito
      t.string :nomesubdistrito
      t.string :localespecifico
      t.string :numcanal  
      t.string :inddecalagem
      t.string :indeducativo
      t.string :indcarater
      t.string :classe
      t.string :indfase
      t.string :medlatitude
      t.string :medlongitude
      t.string :indcoordprefixada
      t.string :frequencia
      t.string :mederpmax
      t.string :deschistorico
      t.text :txtobservacao
      t.string :numconcorrencia
      t.string :anoconcorrencia
      t.string :nomeinteressada
      t.string :indcoordemsitio
      t.string :medlatitudeemsitio
      t.string :medlongitudeemsitio
      t.string :medpotenciadiurna
      t.string :medpotencianoturna
      t.string :medcampocaracteristico
      t.string :inddiretivo
      t.string :medganho
      t.string :medpotencia
      t.string :obsantena
      t.string :medazimalinhdipolos
      t.string :medazimmaxirradiacao
      t.string :horarioinicio1
      t.string :horariofim1
      t.string :horarioinicio2
      t.string :horariofim2
      t.string :numcnpjcpf
      t.string :nomeentidade
      t.string :numfistel
      t.string :numfistelservicoprincipal
      t.string :numprocesso
      t.string :txtcomentario
      t.string :numprocessomc_srd
      t.string :numprocessoportariamc_srd
      t.string :numscradjur
      t.string :numscradtec
      t.string :datacontrato
      t.string :datalimiteinstalacao
      t.string :endlogradouro_sede
      t.string :endnumero_sede
      t.string :endcomplemento_sede
      t.string :endbairro_sede
      t.string :nomemunicipio_sede
      t.string :siglauf_sede
      t.string :codcep_sede
      t.string :endlogradouro_corr
      t.string :endnumero_corr
      t.string :endcomplemento_corr
      t.string :endbairro_corr
      t.string :nomemunicipio_corr
      t.string :siglauf_corr
      t.string :codcep_corr
      t.string :siglasituacao
      t.string :idtpareamento
      t.string :cod_municipio
      t.string :canal_publico 
      t.timestamps
    end
  end
end
